package portal.empleos.picco.enumerations

/**
 * Enum de Idiomas. <br>
 * Ingles_Oral, Ingles_Escrito, Ingles_Lecutra, etc.
 * @author Diego Miglino
 */
enum IdiomaEnum {
	
	INGLES_ORAL("INGLES","ORAL"), INGLES_ESCRITO("INGLES","ESCRITO"), INGLES_LECUTRA("INGLES","LECUTRA"),
	ESPANOL_ORAL("ESPANOL","ORAL"), ESPANOL_ESCRITO("ESPANOL","ESCRITO"), ESPANOL_LECUTRA("ESPANOL","LECUTRA"),
	PORTUGUES_ORAL("PORTUGUES","ORAL"), PORTUGUES_ESCRITO("PORTUGUES","ESCRITO"), PORTUGUES_LECUTRA("PORTUGUES","LECUTRA"),
	FRANCES_ORAL("FRANCES","ORAL"), FRANCES_ESCRITO("FRANCES","ESCRITO"), FRANCES_LECUTRA("FRANCES","LECUTRA"),
	CHINO_ORAL("CHINO","ORAL"), CHINO_ESCRITO("CHINO","ESCRITO"), CHINO_LECUTRA("CHINO","LECUTRA"),
	JAPONES_ORAL("JAPONES","ORAL"), JAPONES_ESCRITO("JAPONES","ESCRITO"), JAPONES_LECUTRA("JAPONES","LECUTRA"),
	ALEMAN_ORAL("ALEMAN","ORAL"), ALEMAN_ESCRITO("ALEMAN","ESCRITO"), ALEMAN_LECUTRA("ALEMAN","LECUTRA"),
	SUECO_ORAL("SUECO","ORAL"), SUECO_ESCRITO("SUECO","ESCRITO"), SUECO_LECUTRA("SUECO","LECUTRA")
	
	private String description
	private String type
	
	IdiomaEnum(String description, String type) {
		this.description = description
		this.type = type
	}

}
